// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AaronDevStack/CRUD_FullStackSolution/Backend/internal/database/ent/address"
	"github.com/AaronDevStack/CRUD_FullStackSolution/Backend/internal/database/ent/predicate"
	"github.com/AaronDevStack/CRUD_FullStackSolution/Backend/internal/database/ent/user"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStreet sets the "street" field.
func (_u *AddressUpdate) SetStreet(v string) *AddressUpdate {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableStreet(v *string) *AddressUpdate {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdate) SetCity(v string) *AddressUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCity(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AddressUpdate) SetState(v string) *AddressUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableState(v *string) *AddressUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetZip sets the "zip" field.
func (_u *AddressUpdate) SetZip(v string) *AddressUpdate {
	_u.mutation.SetZip(v)
	return _u
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableZip(v *string) *AddressUpdate {
	if v != nil {
		_u.SetZip(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdate) SetUpdatedAt(v time.Time) *AddressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AddressUpdate) SetUserID(id int) *AddressUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AddressUpdate) SetUser(v *User) *AddressUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AddressUpdate) ClearUser() *AddressUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := address.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Address.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Zip(); ok {
		if err := address.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "Address.zip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.user"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(address.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Zip(); ok {
		_spec.SetField(address.FieldZip, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetStreet sets the "street" field.
func (_u *AddressUpdateOne) SetStreet(v string) *AddressUpdateOne {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableStreet(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdateOne) SetCity(v string) *AddressUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCity(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *AddressUpdateOne) SetState(v string) *AddressUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableState(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetZip sets the "zip" field.
func (_u *AddressUpdateOne) SetZip(v string) *AddressUpdateOne {
	_u.mutation.SetZip(v)
	return _u
}

// SetNillableZip sets the "zip" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableZip(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetZip(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdateOne) SetUpdatedAt(v time.Time) *AddressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AddressUpdateOne) SetUserID(id int) *AddressUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AddressUpdateOne) SetUser(v *User) *AddressUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AddressUpdateOne) ClearUser() *AddressUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AddressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := address.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := address.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Address.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Zip(); ok {
		if err := address.ZipValidator(v); err != nil {
			return &ValidationError{Name: "zip", err: fmt.Errorf(`ent: validator failed for field "Address.zip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.user"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(address.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Zip(); ok {
		_spec.SetField(address.FieldZip, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
